spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/bxconnect
spring.datasource.username=root
spring.datasource.password=Root2026!@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true